name: docker-build-pushs

on:
  workflow_call:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest    

    steps:
    - name: Check out codes
      uses: actions/checkout@v3.6.0
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REGISTRY_ALIAS: ecrrepo2
        REPOSITORY: ecrrepo2
        IMAGE_TAG: ${{ github.sha }}
      run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME  }} \
          --build-arg DATABASE_HOST=${{ secrets.DATABASE_HOST  }} \
          --build-arg SECRET_KEY=${{ secrets.SECRET_KEY  }} \
          --build-arg DATABASE_USER=${{ secrets.DATABASE_USER  }} \
          --build-arg DATABASE_PASS=${{ secrets.DATABASE_PASS  }} \
          --build-arg DATABASE_ROOT_PASS=${{ secrets.DATABASE_ROOT_PASS  }} \
          --build-arg TESTE_ENV=${{ secrets.TESTE_ENV  }} \
          --no-cache .          
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG