name: docker-build-pushs

on:
  workflow_call:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    env:

    

    steps:
    - uses: actions/checkout@v3.6.0
 
    # - name: Construction of Docker's image
    #   uses: docker/build-push-action@v4.1.1
    #   with:
    #     context: .
    #     file: Dockerfile
    #     push: false
    #     tags: |
    #       renancoradini/denzelcrm:${{ github.sha }}
    #       renancoradini/denzelcrm:${{ github.sha }}
           

    - name: Docker AWS ECR

      uses: appleboy/docker-ecr-action@v0.0.3
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        repo: ecrrepo2
        tags: ${{ github.sha }}
        dockerfile: Dockerfile
        build-args: "SECRET_KEY=eae"
          #  DATABASE_USER=admin
          #  DATABASE_PASS=admin123456
          #  DATABASE_HOST=name1db.cehtpurygiku.us-west-2.rds.amazonaws.com
          #  DATABASE_ROOT_PASS=admin123456
          #  TESTE_ENV=VALOR RECEBIDO VIA GITHUBACTIONS"